# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f19d10eef250090d6b7f863c64af20bd28532de976d0fd5b6a20f73758c4910459289f4e8977dfcbd613cd6b4bbf579eec0ed3f37c53a6d6978492d8f794fd2

test:
  secret_key_base: 41a5a20f6c4ba298507376bc2d4696864ceffefac55034d712b8df23fb9b35d0a8a8276e57bcde476e43f2f0ff3163fd16561ed55d62f956d6bf7935e6209265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
